/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CtoAdvisoryRouteImport } from './routes/cto-advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalsGasStationsRouteImport } from './routes/verticals.gas-stations'
import { Route as VerticalsSlugRouteImport } from './routes/verticals.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CtoAdvisoryRoute = CtoAdvisoryRouteImport.update({
  id: '/cto-advisory',
  path: '/cto-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsGasStationsRoute = VerticalsGasStationsRouteImport.update({
  id: '/verticals/gas-stations',
  path: '/verticals/gas-stations',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsSlugRoute = VerticalsSlugRouteImport.update({
  id: '/verticals/$slug',
  path: '/verticals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cto-advisory': typeof CtoAdvisoryRoute
  '/insights': typeof InsightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verticals/$slug': typeof VerticalsSlugRoute
  '/verticals/gas-stations': typeof VerticalsGasStationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cto-advisory': typeof CtoAdvisoryRoute
  '/insights': typeof InsightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verticals/$slug': typeof VerticalsSlugRoute
  '/verticals/gas-stations': typeof VerticalsGasStationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/cto-advisory': typeof CtoAdvisoryRoute
  '/insights': typeof InsightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verticals/$slug': typeof VerticalsSlugRoute
  '/verticals/gas-stations': typeof VerticalsGasStationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/contact'
    | '/cto-advisory'
    | '/insights'
    | '/sitemap.xml'
    | '/verticals/$slug'
    | '/verticals/gas-stations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/contact'
    | '/cto-advisory'
    | '/insights'
    | '/sitemap.xml'
    | '/verticals/$slug'
    | '/verticals/gas-stations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/contact'
    | '/cto-advisory'
    | '/insights'
    | '/sitemap.xml'
    | '/verticals/$slug'
    | '/verticals/gas-stations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  ContactRoute: typeof ContactRoute
  CtoAdvisoryRoute: typeof CtoAdvisoryRoute
  InsightsRoute: typeof InsightsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerticalsSlugRoute: typeof VerticalsSlugRoute
  VerticalsGasStationsRoute: typeof VerticalsGasStationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cto-advisory': {
      id: '/cto-advisory'
      path: '/cto-advisory'
      fullPath: '/cto-advisory'
      preLoaderRoute: typeof CtoAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/gas-stations': {
      id: '/verticals/gas-stations'
      path: '/verticals/gas-stations'
      fullPath: '/verticals/gas-stations'
      preLoaderRoute: typeof VerticalsGasStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/$slug': {
      id: '/verticals/$slug'
      path: '/verticals/$slug'
      fullPath: '/verticals/$slug'
      preLoaderRoute: typeof VerticalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  ContactRoute: ContactRoute,
  CtoAdvisoryRoute: CtoAdvisoryRoute,
  InsightsRoute: InsightsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerticalsSlugRoute: VerticalsSlugRoute,
  VerticalsGasStationsRoute: VerticalsGasStationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
